# Generated by Django 3.2.3 on 2021-06-06 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=255)),
                ('abbreviation', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'ewallet_category',
            },
        ),
    ]
