# Generated by Django 3.2.3 on 2021-06-06 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.PositiveIntegerField(choices=[(0, 'BUY'), (1, 'SELL')])),
                ('quantity', models.DecimalField(decimal_places=10, default=0.0, max_digits=15)),
                ('date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asset.asset')),
            ],
            options={
                'db_table': 'ewallet_order',
            },
        ),
    ]
