# Generated by Django 3.2.3 on 2021-06-06 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='asset',
            new_name='asset_id',
        ),
    ]
