# Generated by Django 3.2.3 on 2021-06-06 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0003_tokenproxy'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='token',
            options={},
        ),
        migrations.RemoveField(
            model_name='token',
            name='created',
        ),
        migrations.RemoveField(
            model_name='token',
            name='key',
        ),
        migrations.RemoveField(
            model_name='token',
            name='user',
        ),
        migrations.AddField(
            model_name='token',
            name='token_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authtoken.token'),
            preserve_default=False,
        ),
    ]
