# Generated by Django 3.2.3 on 2021-06-06 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210606_1937'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='account',
            table='ewallet_account',
        ),
        migrations.AlterModelTable(
            name='token',
            table='ewallet_token',
        ),
    ]
