# Generated by Django 3.2.3 on 2021-06-06 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asset', '0001_initial'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('investment_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=10, default=1.0, max_digits=15)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset', to='asset.asset')),
            ],
            options={
                'db_table': 'ewallet_investment',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('wallet_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=255)),
                ('describe', models.TextField(blank=True, default=None, max_length=255, null=True)),
                ('balance', models.DecimalField(decimal_places=10, default=0.0, max_digits=15)),
                ('category_id', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, to='category.category')),
                ('investment', models.ManyToManyField(through='wallet.Investment', to='asset.Asset')),
            ],
            options={
                'db_table': 'ewallet_wallet',
            },
        ),
        migrations.AddField(
            model_name='investment',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='wallet.wallet'),
        ),
    ]
